ui:
  # @hidden
  image: icr.io/ai-services-cicd/rag-ui:v0.0.17

instruct:
  image: registry.redhat.io/rhaiis/vllm-spyre-rhel9:3.2.5
  imagePullSecret: "redhat-registry-secret"

embedding:
  image: icr.io/ppc64le-oss/vllm-ppc64le:0.9.1
  imagePullSecret: "icr-secret"

reranker:
  image: icr.io/ppc64le-oss/vllm-ppc64le:0.9.1
  imagePullSecret: "icr-secret"

backend:
  # @hidden
  image: icr.io/ai-services-private/rag:v0.0.27
  # @hidden
  log_level: "INFO"

ingest:
  # @hidden
  log_level: "INFO"

opensearch:
  # @hidden
  image: icr.io/ai-services-private/opensearch:3.3.0-ppc64le
  # @description Sets the memory limit for the Opensearch service(Default: 4Gi). Override by passing a value with a unit suffix (e.g., Mi, Gi).
  memoryLimit: 4Gi
  auth:
    username: "admin"
    password: "AiServices@1234"
