name: Minio
on:
  push:
    paths:
      - 'images/**'
    branches:
      - main
  
  # pull_request:
  # branches:
  #     - main
  
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

env:
  ICR_REGISTRY: icr.io
  ICR_NAMESPACE: ai-services-cicd

jobs:
  build-publish-image:
    name: minio
    runs-on: ubuntu-24.04-ppc64le

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Podman login
        run: |
          echo ${{ secrets.ICR_APIKEY }} | podman login ${{ env.ICR_REGISTRY }} -u ${{ secrets.ICR_USERNAME }} --password-stdin
      
      - name: Build minio image
        working-directory: images/minio
        run: |
          make build REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}

      - name: Publish minio image
        working-directory: images/minio
        run: |
          make push REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }} REGISTRY_USER=${{ secrets.ICR_USERNAME }} REGISTRY_PASSWORD=${{ secrets.ICR_APIKEY }}
